// Rasterize the "Liquid + Depth" glass weather icons to PNG and embed them,
// base64, into widget/nebel-widget.js (between the GLASS ICONS markers).
//
// The Scriptable widget is a single self-contained file, so the icons live
// inline rather than being fetched or hosted.
//
// Run: npm run build:widget   (after changing icons or the treatment)

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { Resvg } from '@resvg/resvg-js'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(ROOT, 'src', 'icons', 'meteocons')
const WIDGET = join(ROOT, 'widget', 'nebel-widget.js')
const SIZE = 180 // px — ~3x the widget hero, downscales cleanly for the hourly row

const LIGHTEN_TOP = 0.34
const DARKEN_BOTTOM = 0.3

function parts(svg) {
  const o = svg.indexOf('>') + 1
  const c = svg.lastIndexOf('</svg>')
  return { inner: svg.slice(o, c).trim(), vb: (svg.match(/viewBox="([^"]+)"/) || [])[1] || '0 0 128 128' }
}
const hex = (c) =>
  c === 'white' ? [255, 255, 255] : c === 'black' ? [0, 0, 0] : [0, 2, 4].map((i) => parseInt(c.replace('#', '').slice(i, i + 2), 16))
const toHex = (r) => '#' + r.map((v) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0')).join('')
const mix = (a, b, t) => a.map((v, i) => v + (b[i] - v) * t)

function intensify(inner) {
  return inner.replace(/<linearGradient[\s\S]*?<\/linearGradient>/g, (g) =>
    g.replace(/<stop([^>]*)\/>/g, (s, a) => {
      const off = parseFloat((a.match(/offset="([^"]+)"/) || [, '0'])[1]) || 0
      const cm = a.match(/stop-color="([^"]+)"/)
      if (!cm) return s
      let rgb = hex(cm[1])
      rgb = mix(rgb, [255, 255, 255], (1 - off) * LIGHTEN_TOP)
      rgb = mix(rgb, [0, 0, 0], off * DARKEN_BOTTOM)
      return `<stop${a.replace(/stop-color="[^"]+"/, `stop-color="${toHex(rgb)}"`)}/>`
    }),
  )
}

function nsIds(inner, p) {
  const ids = [...inner.matchAll(/id="([^"]+)"/g)].map((m) => m[1]).sort((a, b) => b.length - a.length)
  for (const id of ids) {
    const esc = id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    inner = inner.replace(new RegExp(`id="${esc}"`, 'g'), `id="${p}-${id}"`)
    inner = inner.replace(new RegExp(`#${esc}(?=["')])`, 'g'), `#${p}-${id}`)
  }
  return inner
}

function treat(raw, p) {
  const { inner, vb } = parts(raw)
  const tpl = nsIds(intensify(inner), p)
  const defs =
    `<defs><linearGradient id="${p}-gloss" x1="0" y1="0" x2="0" y2="1">` +
    `<stop offset="0" stop-color="#fff" stop-opacity=".72"/>` +
    `<stop offset=".45" stop-color="#fff" stop-opacity="0"/></linearGradient>` +
    `<g id="${p}-icon">${tpl}</g>` +
    `<mask id="${p}-mask" style="mask-type:alpha" maskUnits="userSpaceOnUse"><use href="#${p}-icon"/></mask></defs>`
  const body = `<use href="#${p}-icon"/><rect width="128" height="128" fill="url(#${p}-gloss)" mask="url(#${p}-mask)"/>`
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb}">${defs}${body}</svg>`
}

function rasterize(svg) {
  const r = new Resvg(svg, { fitTo: { mode: 'width', value: SIZE }, background: 'rgba(0,0,0,0)' })
  return r.render().asPng()
}

const files = readdirSync(SRC).filter((f) => f.endsWith('.svg')).sort()
const entries = files
  .map((f) => {
    const name = f.replace('.svg', '')
    const svg = treat(readFileSync(join(SRC, f), 'utf8'), name.replace(/[^a-z0-9]/gi, ''))
    const b64 = rasterize(svg).toString('base64')
    return `  ${JSON.stringify(name)}: '${b64}',`
  })
  .join('\n')

const block =
  `// === GLASS ICONS — base64 PNGs generated by scripts/build-widget.mjs; do not edit ===\n` +
  `const NEBEL_ICONS = {\n${entries}\n}\n` +
  `// === END GLASS ICONS ===`

const src = readFileSync(WIDGET, 'utf8')
const updated = src.replace(
  /\/\/ === GLASS ICONS[\s\S]*?\/\/ === END GLASS ICONS ===/,
  block,
)
writeFileSync(WIDGET, updated)

const kb = (Buffer.byteLength(updated) / 1024).toFixed(0)
console.log(`embedded ${files.length} glass icons (${SIZE}px) — widget/nebel-widget.js is now ${kb} KB`)
